export const TOPICS = [
  // Engineering & Aerospace
  { id: 'rocket-science', name: 'Rocket Science', icon: 'rocket', isProgramming: false },
  { id: 'aerospace-engineering', name: 'Aerospace Engineering', icon: 'aerospace', isProgramming: false },
  { id: 'orbital-mechanics', name: 'Orbital Mechanics', icon: 'orbit', isProgramming: true },
  { id: 'aerospace-materials', name: 'Aerospace Materials', icon: 'materials', isProgramming: false },
  { id: 'computational-fluid-dynamics', name: 'Computational Fluid Dynamics', icon: 'fluid', isProgramming: true },
  { id: 'aerodynamics', name: 'Aerodynamics', icon: 'aerodynamics', isProgramming: false },
  { id: 'satellite-robotics', name: 'Satellite & Robotics', icon: 'satellite', isProgramming: true },
  { id: 'rocket-component-design', name: 'Rocket Component Design', icon: 'component', isProgramming: false },
  { id: 'control-systems', name: 'Control Systems Engineering', icon: 'control', isProgramming: true },
  { id: 'mechatronics', name: 'Mechatronics', icon: 'mechatronics', isProgramming: true },
  { id: 'autonomous-vehicles', name: 'Autonomous Vehicles', icon: 'autonomous', isProgramming: true },
  { id: 'freecad', name: 'FreeCAD', icon: 'freecad', isProgramming: false },
  { id: 'fusion-360', name: 'Autodesk Fusion 360', icon: 'fusion-360', isProgramming: false },
  { id: 'catia', name: 'CATIA', icon: 'catia', isProgramming: false },
  
  // AI & Machine Learning
  { id: 'artificial-intelligence', name: 'Artificial Intelligence', icon: 'ai', isProgramming: true },
  { id: 'generative-ai', name: 'Generative AI', icon: 'generative-ai', isProgramming: true },
  { id: 'reinforcement-learning', name: 'Reinforcement Learning', icon: 'rl', isProgramming: true },
  { id: 'explainable-ai', name: 'Explainable AI (XAI)', icon: 'xai', isProgramming: true },
  { id: 'quantum-machine-learning', name: 'Quantum Machine Learning', icon: 'qml', isProgramming: true },
  { id: 'natural-language-processing', name: 'Natural Language Processing', icon: 'nlp', isProgramming: true },
  { id: 'computer-vision', name: 'Computer Vision', icon: 'vision', isProgramming: true },
  { id: 'recommender-systems', name: 'Recommender Systems', icon: 'recommender', isProgramming: true },
  { id: 'swarm-intelligence', name: 'Swarm Intelligence', icon: 'swarm', isProgramming: true },
  { id: 'federated-learning', name: 'Federated Learning', icon: 'federated', isProgramming: true },
  
  // Data & Computing
  { id: 'data-science', name: 'Data Science & Big Data', icon: 'data-science', isProgramming: true },
  { id: 'systems-design', name: 'Systems Design', icon: 'systems', isProgramming: false },
  { id: 'cloud-computing', name: 'Cloud Computing', icon: 'cloud', isProgramming: true },
  { id: 'devops-automation', name: 'DevOps & Automation', icon: 'devops', isProgramming: true },
  { id: 'high-performance-computing', name: 'High-Performance Computing', icon: 'hpc', isProgramming: true },
  { id: 'quantum-computing', name: 'Quantum Computing', icon: 'quantum', isProgramming: true },
  { id: 'edge-computing', name: 'Edge Computing', icon: 'edge', isProgramming: true },
  { id: 'simulation-modeling', name: 'Simulation & Modeling', icon: 'simulation', isProgramming: true },
  { id: 'knowledge-graphs', name: 'Knowledge Graphs', icon: 'graph', isProgramming: true },

  // Cybersecurity
  { id: 'cybersecurity', name: 'Cybersecurity', icon: 'cybersecurity', isProgramming: true },
  { id: 'ethical-hacking', name: 'Ethical Hacking', icon: 'ethical-hacking', isProgramming: true },
  { id: 'digital-forensics', name: 'Digital Forensics', icon: 'forensics', isProgramming: true },
  { id: 'blockchain-dev', name: 'Blockchain Development', icon: 'blockchain', isProgramming: true },
  { id: 'cryptography', name: 'Cryptography', icon: 'crypto', isProgramming: true },
  { id: 'quantum-cryptography', name: 'Quantum Cryptography', icon: 'quantum-crypto', isProgramming: true },

  // Software Development
  { id: 'game-development', name: 'Game Development', icon: 'game', isProgramming: true },
  { id: 'ar-vr', name: 'AR/VR Development', icon: 'ar-vr', isProgramming: true },
  { id: 'iot-development', name: 'IoT Development', icon: 'iot', isProgramming: true },
  { id: 'network-programming', name: 'Network Programming', icon: 'network', isProgramming: true },
  { id: 'embedded-systems', name: 'Embedded Systems', icon: 'embedded', isProgramming: true },
  { id: 'human-computer-interaction', name: 'Human-Computer Interaction', icon: 'hci', isProgramming: false },
  { id: 'frontend-development', name: 'Frontend Web Development', icon: 'frontend', isProgramming: true },
  { id: 'backend-development', name: 'Backend Web Development', icon: 'backend', isProgramming: true },
  { id: 'fullstack-development', name: 'Full-Stack Web Development', icon: 'fullstack', isProgramming: true },
  { id: 'mobile-app-dev-ios', name: 'iOS App Development (Swift)', icon: 'ios', isProgramming: true },
  { id: 'mobile-app-dev-android', name: 'Android App Development (Kotlin)', icon: 'android', isProgramming: true },
  { id: 'database-sql', name: 'SQL & Database Management', icon: 'sql', isProgramming: true },
  { id: 'database-nosql', name: 'NoSQL Databases (MongoDB)', icon: 'nosql', isProgramming: true },

  // Scientific & Computational Fields
  { id: 'computational-biology', name: 'Computational Biology', icon: 'comp-bio', isProgramming: true },
  { id: 'bioinformatics', name: 'Bioinformatics', icon: 'bioinformatics', isProgramming: true },
  { id: 'geospatial-analysis', name: 'Geospatial Analysis', icon: 'geospatial', isProgramming: true },
  { id: 'digital-twin-tech', name: 'Digital Twin Technology', icon: 'digital-twin', isProgramming: true },
  { id: 'neuromorphic-computing', name: 'Neuromorphic Computing', icon: 'neuromorphic', isProgramming: true },
  { id: 'photonics-plasmonics', name: 'Photonics & Plasmonics', icon: 'photonics', isProgramming: false },
  { id: 'materials-informatics', name: 'Materials Informatics', icon: 'materials-info', isProgramming: true },
  { id: 'drug-discovery', name: 'Computational Drug Discovery', icon: 'drug-discovery', isProgramming: true },
  { id: 'climate-modeling', name: 'Climate Modeling', icon: 'climate', isProgramming: true },
  { id: 'computational-chemistry', name: 'Computational Chemistry', icon: 'chemistry', isProgramming: true },
  { id: 'signal-processing', name: 'Digital Signal Processing', icon: 'signal', isProgramming: true },
  { id: 'bio-signal-processing', name: 'Bio-Signal Processing (EEG/ECG)', icon: 'bio-signal', isProgramming: true },
  { id: 'seismic-analysis', name: 'Seismic Data Analysis', icon: 'seismic', isProgramming: true },
  { id: 'computational-linguistics', name: 'Computational Linguistics', icon: 'compling', isProgramming: true },
  { id: 'astrobiology', name: 'Astrobiology', icon: 'astrobiology', isProgramming: false },

  // Business & Finance
  { id: 'financial-engineering', name: 'Financial Engineering (FinTech)', icon: 'fintech', isProgramming: true },
  { id: 'supply-chain-optimization', name: 'Supply Chain Optimization', icon: 'supply-chain', isProgramming: true },
  { id: 'operations-research', name: 'Operations Research', icon: 'operations', isProgramming: true },
  { id: 'robotics-process-automation', name: 'Robotics Process Automation', icon: 'robotics', isProgramming: true },
  { id: 'hotel-management', name: 'Hotel Management', icon: 'hotel-management', isProgramming: false },
  { id: 'microeconomics', name: 'Microeconomics', icon: 'microeconomics', isProgramming: false },
  { id: 'macroeconomics', name: 'Macroeconomics', icon: 'macroeconomics', isProgramming: false },
  { id: 'corporate-finance', name: 'Corporate Finance', icon: 'corp-finance', isProgramming: false },
  { id: 'investment-analysis', name: 'Investment Analysis', icon: 'investment', isProgramming: false },
  { id: 'accounting-principles', name: 'Accounting Principles', icon: 'accounting', isProgramming: false },
  { id: 'project-management-agile', name: 'Agile & Scrum', icon: 'agile', isProgramming: false },
  
  // Foundational Mathematics
  { id: 'math-arithmetic', name: 'Basic Arithmetic', icon: 'arithmetic', isProgramming: false },
  { id: 'math-pre-algebra', name: 'Pre-Algebra', icon: 'pre-algebra', isProgramming: false },
  { id: 'math-algebra-1', name: 'Algebra I', icon: 'algebra', isProgramming: false },
  { id: 'math-geometry', name: 'Geometry', icon: 'geometry', isProgramming: false },
  { id: 'math-algebra-2', name: 'Algebra II & Trigonometry', icon: 'algebra-2', isProgramming: false },
  { id: 'math-statistics', name: 'Probability & Statistics', icon: 'statistics', isProgramming: true },
  { id: 'math-pre-calculus', name: 'Pre-Calculus', icon: 'pre-calculus', isProgramming: false },
  { id: 'math-calculus-1', name: 'Calculus I (Derivatives)', icon: 'calculus-1', isProgramming: false },
  { id: 'math-calculus-2', name: 'Calculus II (Integrals)', icon: 'calculus-2', isProgramming: false },
  { id: 'math-calculus-3', name: 'Multivariable Calculus', icon: 'calculus-3', isProgramming: false },
  { id: 'math-linear-algebra', name: 'Linear Algebra', icon: 'linear-algebra', isProgramming: true },
  { id: 'math-differential-equations', name: 'Differential Equations', icon: 'diffeq', isProgramming: true },

  // Foundational Science
  { id: 'science-physics', name: 'Physics I (Mechanics)', icon: 'physics', isProgramming: false },
  { id: 'science-physics-em', name: 'Physics II (E&M)', icon: 'physics-em', isProgramming: false },
  { id: 'science-chemistry', name: 'General Chemistry', icon: 'gen-chem', isProgramming: false },
  { id: 'science-organic-chemistry', name: 'Organic Chemistry', icon: 'org-chem', isProgramming: false },
  { id: 'science-biology', name: 'General Biology', icon: 'biology', isProgramming: false },
  { id: 'science-genetics', name: 'Genetics', icon: 'genetics', isProgramming: false },
  { id: 'science-earth-science', name: 'Earth Science', icon: 'earth-science', isProgramming: false },
  { id: 'science-astronomy', name: 'Astronomy', icon: 'astronomy', isProgramming: false },
  { id: 'science-particle-physics', name: 'Particle Physics', icon: 'particle', isProgramming: false },
  { id: 'science-astrophysics', name: 'Astrophysics', icon: 'astrophysics', isProgramming: false },
  
  // Foundational English & Communication
  { id: 'english-grammar', name: 'Grammar & Punctuation', icon: 'grammar', isProgramming: false },
  { id: 'english-composition', name: 'Essay Writing & Composition', icon: 'composition', isProgramming: false },
  { id: 'english-literature', name: 'Literature Analysis', icon: 'literature', isProgramming: false },
  { id: 'english-creative-writing', name: 'Creative Writing', icon: 'creative-writing', isProgramming: false },
  { id: 'english-technical-writing', name: 'Technical Writing', icon: 'tech-writing', isProgramming: false },
  { id: 'english-public-speaking', name: 'Public Speaking', icon: 'public-speaking', isProgramming: false },
  
  // Arts & Humanities
  { id: 'arts-world-history', name: 'World History', icon: 'history', isProgramming: false },
  { id: 'arts-philosophy', name: 'Philosophy', icon: 'philosophy', isProgramming: false },
  { id: 'arts-psychology', name: 'Psychology', icon: 'psychology', isProgramming: false },
  { id: 'arts-music-theory', name: 'Music Theory', icon: 'music', isProgramming: false },
];
